name: Test
on: [ push, workflow_dispatch ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Run lint
        run: ./gradlew lintDebug
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
      - name: Run tests
        run: ./gradlew testDebug
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
